#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#EMOCIONES

emocion:
  path: /emocion/{id_emocion}
  controller: App\Controller\EmocionesController:emocion
  methods: [GET, PUT, DELETE]

emociones:
  path: /emociones
  controller: App\Controller\EmocionesController:emociones
  methods: [GET, POST]

#USUARIO

logearUsuario:
  path: /logearUsuario
  controller: App\Controller\UsuarioController::logearUsuario
  methods: [POST]

usuarios:
  path: /usuarios
  controller: App\Controller\UsuarioController::usuarios
  methods: [GET, POST]

usuario:
  path: /usuario/{id}
  controller: App\Controller\UsuarioController::usuario
  methods: [GET, PUT, DELETE]

#DATOS

datos:
  path: /datos/{id}
  controller: App\Controller\DatosController::datos
  methods: [GET, POST, DELETE]

dato:
  path: /dato
  controller: App\Controller\DatosController::dato
  methods: [GET]

#EMOCIONES_USUARIO

info:
  path: /usuario/{id_usuario}/emocion/{id_emocion}
  controller: App\Controller\EmocionesUsuarioController::info
  methods: [GET, POST]

